import Head from 'next/head';
import Board from 'components/Board';
import { GameProvider } from 'components/Game';
import Status from 'components/Status';

export default function Home() {
  return (
    <>
      <Head>
        <title>Chess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <GameProvider>
          <div style={{ display: 'flex' }}>
            <div style={{ width: 800 }}>
              <Board />
            </div>
            <Status />
          </div>
        </GameProvider>
      </main>
    </>
  );
}
